# Generated by Django 6.0.2 on 2026-02-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Eng.', 'Eng.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.')], max_length=10, verbose_name='Title'),
        ),
    ]
