# Generated by Django 6.0.2 on 2026-02-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_alter_customuser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20, verbose_name='Membership Status'),
        ),
    ]
