# Generated by Django 6.0.2 on 2026-02-06 22:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Organization"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Inquiry"),
                            ("MEMBERSHIP", "Membership Inquiry"),
                            ("EVENT", "Event Inquiry"),
                            ("TECH_SUPPORT", "Technical Support"),
                            ("PARTNERSHIP", "Partnership Inquiry"),
                            ("FEEDBACK", "Feedback"),
                        ],
                        max_length=50,
                        verbose_name="Message Type",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                (
                    "is_responded",
                    models.BooleanField(default=False, verbose_name="Responded"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                ("response", models.TextField(blank=True, verbose_name="Response")),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Responded At"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Short Description"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CONFERENCE", "Conference"),
                            ("WORKSHOP", "Workshop"),
                            ("SEMINAR", "Seminar"),
                            ("WEBINAR", "Webinar"),
                            ("TRAINING", "Training"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Event Type",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                ("end_date", models.DateTimeField(verbose_name="End Date")),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Registration Deadline"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Location"
                    ),
                ),
                ("venue", models.TextField(blank=True, verbose_name="Venue Details")),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="Online Event"),
                ),
                (
                    "online_link",
                    models.URLField(blank=True, verbose_name="Online Link"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="events/", verbose_name="Event Image"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        upload_to="events/banners/",
                        verbose_name="Event Banner",
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=True, verbose_name="Free Event"),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Registration Fee",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Capacity"
                    ),
                ),
                (
                    "registered_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Registered Count"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="Slug"),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Meta Description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "attended",
                    models.BooleanField(default=False, verbose_name="Attended"),
                ),
                (
                    "attendance_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Attendance Date"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("REFUNDED", "Refunded"),
                            ("NOT_REQUIRED", "Not Required"),
                        ],
                        default="NOT_REQUIRED",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transaction ID"
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(blank=True, verbose_name="Additional Notes"),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=True, verbose_name="Confirmed"),
                ),
                (
                    "confirmation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Confirmation Date"
                    ),
                ),
                (
                    "confirmation_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Confirmation Code"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-registration_date"],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("PRESIDENT", "President"),
                            ("VICE_PRESIDENT", "Vice President"),
                            ("SECRETARY", "Secretary"),
                            ("TREASURER", "Treasurer"),
                            ("EXECUTIVE_MEMBER", "Executive Member"),
                            ("REGIONAL_REP", "Regional Representative"),
                        ],
                        max_length=50,
                        verbose_name="Position",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NORTH", "North Africa"),
                            ("EAST", "East Africa"),
                            ("WEST", "West Africa"),
                            ("CENTRAL", "Central Africa"),
                            ("SOUTHERN", "Southern Africa"),
                        ],
                        max_length=50,
                        verbose_name="Region",
                    ),
                ),
                ("term_start", models.DateField(verbose_name="Term Start")),
                ("term_end", models.DateField(verbose_name="Term End")),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="Current Member"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(default=False, verbose_name="Show on Homepage"),
                ),
                ("biography", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "achievements",
                    models.TextField(blank=True, verbose_name="Key Achievements"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, verbose_name="LinkedIn Profile"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, verbose_name="Twitter Profile"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Executive Member",
                "verbose_name_plural": "Executive Members",
                "ordering": ["display_order", "position"],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EVENT", "Events"),
                            ("CONFERENCE", "Conferences"),
                            ("WORKSHOP", "Workshops"),
                            ("COMMITTEE", "Committee Meetings"),
                            ("GENERAL", "General"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="gallery/", verbose_name="Image"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="gallery/thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured Image"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Plan Name")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Member (National Association)"),
                            ("AFFILIATE", "Affiliate Member (Regional Organization)"),
                            ("ASSOCIATE", "Associate Member (Organization/Individual)"),
                            ("HONORARY", "Honorary Member"),
                            ("STUDENT", "Student Member"),
                        ],
                        max_length=50,
                        verbose_name="Plan Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Annual Fee"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Duration (Months)"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text="List of features as JSON array",
                        verbose_name="Features",
                    ),
                ),
                ("benefits", models.TextField(blank=True, verbose_name="Benefits")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Popular Plan"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Membership Plan",
                "verbose_name_plural": "Membership Plans",
                "ordering": ["display_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Excerpt"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("RESEARCH", "Research"),
                            ("POLICY", "Policy & Advocacy"),
                            ("EDUCATION", "Education"),
                            ("TECHNOLOGY", "Technology"),
                            ("AWARD", "Awards & Recognition"),
                            ("PARTNERSHIP", "Partnership"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="news/", verbose_name="News Image"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="news/thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Publish Date"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="Slug"),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Meta Description"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags",
                        max_length=500,
                        verbose_name="Tags",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0, verbose_name="Views")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Organization Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("CORPORATE", "Corporate Partner"),
                            ("ACADEMIC", "Academic Institution"),
                            ("GOVERNMENT", "Government Agency"),
                            ("NGO", "Non-Governmental Organization"),
                            ("INTERNATIONAL", "International Organization"),
                            ("SPONSOR", "Sponsor"),
                        ],
                        max_length=50,
                        verbose_name="Partner Type",
                    ),
                ),
                ("website", models.URLField(verbose_name="Website")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "logo",
                    models.ImageField(upload_to="partners/logos/", verbose_name="Logo"),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        upload_to="partners/banners/",
                        verbose_name="Banner Image",
                    ),
                ),
                (
                    "partnership_date",
                    models.DateField(verbose_name="Partnership Start Date"),
                ),
                (
                    "partnership_active",
                    models.BooleanField(
                        default=True, verbose_name="Active Partnership"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(default=False, verbose_name="Show on Homepage"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="Slug"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "auto_renew",
                    models.BooleanField(default=True, verbose_name="Auto Renew"),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount Paid"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("PAYPAL", "PayPal"),
                        ],
                        max_length=50,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transaction ID"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "mobile_network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MTN", "MTN"),
                            ("AIRTEL", "Airtel"),
                            ("VODAFONE", "Vodafone"),
                            ("ORANGE", "Orange"),
                        ],
                        max_length=50,
                        verbose_name="Mobile Network",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Mobile Number"
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Receipt Number"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
