# Generated by Django 6.0.2 on 2026-02-10 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abea_app", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="charges",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Transaction Charges",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_notes",
            field=models.TextField(blank=True, verbose_name="Payment Notes"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="reference_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Reference Number"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Verified At"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="webhook_payload",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Webhook Payload"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="webhook_received",
            field=models.BooleanField(default=False, verbose_name="Webhook Received"),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["transaction_id"], name="abea_app_su_transac_e42f61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["reference_number"], name="abea_app_su_referen_5c76db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["payment_status", "is_active"],
                name="abea_app_su_payment_3bfd12_idx",
            ),
        ),
    ]
