# Generated by Django 6.0.2 on 2026-02-16 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abea_app", "0003_subscription_charges_subscription_payment_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("transaction_id",), name="unique_transaction_id"
            ),
        ),
    ]
