# Generated by Django 6.0.2 on 2026-02-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abea_app", "0004_subscription_unique_transaction_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_transaction_id",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="transaction_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Transaction ID"
            ),
        ),
    ]
